version: '3.7'

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: nba_database
    environment:
      MYSQL_DATABASE: 'nba'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - '3308:3306'
    volumes:
      - ./database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: nba_database_phpmyadmin
    environment:
      PMA_HOST: 'db'
      PMA_USER: 'admin'
      PMA_PASSWORD: 'password'
    ports:
      - '8080:80'
