version: '3.7'

services:
  db:
    env_file: '.env'
    image: mysql:${MYSQL_VERSION}
    restart: always
    container_name: nba_database
    ports:
      - '3308:3306'
    volumes:
      - ./database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: nba_database_phpmyadmin
    environment:
      PMA_HOST: 'db'
      PMA_USER: 'root'
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '8080:80'
