from ddl.draft import create_table_draft
from ddl.games import create_table_games
from ddl.lineups import create_table_lineups
from ddl.players import create_table_players
from ddl.playoffs import create_table_playoffs
from ddl.plays import create_table_plays
from ddl.plays_players import create_table_plays_players
from ddl.standings import create_table_standings
from ddl.teams import create_table_teams
from ddl.transactions import create_table_transactions
